### REGISTER
POST https://alfred-server.up.railway.app/client/register
Content-Type: application/json

{
    "email": "client@example.com",
    "name": "client",
    "password":"client",
    "email": "client@example.com",
    "name": "client",
    "password":"client",
    "phone_number":"123",
    "address":"local",
    "image_url":"images"
}

### LOGIN
POST https://alfred-server.up.railway.app/client/login
Content-Type: application/json

{
    "email": "client@example.com",
    "password": "client",
    "email": "client@example.com",
    "password": "client"
}

### GET CLIENT BY ID
GET http://localhost:8080/client/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U
GET http://localhost:8080/client/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U

### UPDATE CLIENT DATA
PATCH http://localhost:8080/client/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U
PATCH http://localhost:8080/client/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U
Content-Type: application/json

{
    "name":"budi1",
    "address":"localhost"
}

### CHANGE PASSWORD
PATCH http://localhost:8080/client/change-password/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U
PATCH http://localhost:8080/client/change-password/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U
Content-Type: application/json

{
    "old_password":"client",
    "new_password":"clientNewPassword"
}

### POST A JOB
POST https://alfred-server.up.railway.app/job/create-job/8ccfe16f-902f-11ee-897a-eec53a9db58b
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhjY2ZlMTZmLTkwMmYtMTFlZS04OTdhLWVlYzUzYTlkYjU4YiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTUxMDg0OX0.YFmCP_wsmKUxmdUrJ6YEXO78VWuJ_fbeJiZzhdI7-XA
Content-Type: application/json

{
    "name": "Bersih-bersih kebun kelas 2",
    "description": "Bersih-bersih kebun 10 hektar",
    "address": "Jl. Jalan-jalan no 54 Jakarta",
    "latitude": -7.1234,
    "longitude": 108.1234,
    "imageURL":"abcde"
}

POST http://localhost:8080/bidlist/create-bidlist/
Authorization: Bearer
Content-Type: application/json

{
    "job_id": "ebbaa178-a260-4da0-9020-bacc68faad96",
    "bidder_id": "ebbaa178-a260-4da0-9020-bacc68faad96",
    "priceOnBid": 100000,
}