### REGISTER
POST http://localhost:8080/client/register
Content-Type: application/json

{
    "email": "client2@example.com",
    "name": "client2",
    "password":"client2",
    "phone_number":"123",
    "address":"local",
    "image_url":"images"
}

### LOGIN
POST http://localhost:8080/client/login
Content-Type: application/json

{
    "email": "client1@example.com",
    "password": "client1"
}

### BASE TEST
GET http://localhost:8080