### REGISTER
POST http://localhost:8080/client/register
Content-Type: application/json

{
    "email": "client@example.com",
    "name": "client",
    "password":"client",
    "phone_number":"123",
    "address":"local",
    "image_url":"images"
}

### LOGIN
POST http://localhost:8080/client/login
Content-Type: application/json

{
    "email": "client@example.com",
    "password": "client"
}

### GET CLIENT BY ID
GET http://localhost:8080/client/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U

### UPDATE CLIENT DATA
PATCH http://localhost:8080/client/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U
Content-Type: application/json

{
    "name":"budi1",
    "address":"localhost"
}

### CHANGE PASSWORD
PATCH http://localhost:8080/client/change-password/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U
Content-Type: application/json

{
    "old_password":"client",
    "new_password":"clientNewPassword"
}

### POST A JOB
POST https://alfred-server.up.railway.app/job/create-job/ebbaa178-a260-4da0-9020-bacc68faad96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViYmFhMTc4LWEyNjAtNGRhMC05MDIwLWJhY2M2OGZhYWQ5NiIsImVtYWlsIjoiY2xpZW50QGV4YW1wbGUuY29tIiwicm9sZSI6ImNsaWVudCIsImV4cCI6MTcwMTA2MTUyNn0.SA3S3dFFgBA1Llv3njkgumzSG9V_obrA-WK00i21F1U
Content-Type: application/json

{
    "name": "Bersih-bersih kebun kelas 2",
    "description": "Bersih-bersih kebun 10 hektar",
    "address": "Jl. Jalan-jalan no 54 Jakarta",
    "latitude": -7.1234,
    "longitude": 108.1234,
    "imageURL":"abcde"
}

### GET JOB BY JOB ID
GET http://localhost:8080/job/00b18d1d-91e5-4903-9434-53cd703489e2

### GET ALL JOB
GET http://localhost:8080/job


### REGISTER TALENT
POST http://localhost:8080/talent/register
Content-Type: application/json

{
    "email": "talent@example.com",
    "name": "talent",
    "password":"talent",
    "phone_number":"123",
    "address":"local",
    "image_url":"images"
}

### LOGIN TALENT
POST http://localhost:8080/talent/login
Content-Type: application/json

{
    "email": "talent@example.com",
    "password": "talent"
}